export const GET_MOVIE_INFO_REQUEST = "GET_MOVIE_INFO_REQUEST";
export const GET_MOVIE_INFO_SUCCESS = "GET_MOVIE_INFO_SUCCESS";
export const GET_MOVIE_INFO_FAIL ="GET_MOVIE_INFO_FAIL";

export const UPDATE_MOVIE="UPDATE_MOVIE"

