export const GET_USER_INFOR_REQUEST ="GET_USER_INFOR_REQUEST";
export const GET_USER_INFOR_SUCCESS ="GET_USER_INFOR_SUCCESS";
export const GET_USER_INFOR_FAIL ="GET_USER_INFOR_FAIL";
export const CLEAR_USER_INFOR = "CLEAR_USER_INFOR";

export const UPDATE_USER_INFO_REQUEST ="UPDATE_USER_INFO_REQUEST";
export const UPDATE_USER_INFO_SUCCESS ="UPDATE_USER_INFO_SUCCESS";
export const UPDATE_USER_INFO_FAIL ="UPDATE_USER_INFO_FAIL";

export const LAY_DANH_SACH_RAP = "LAY_DANH_SACH_RAP";