export const GET_MOVIE_LIST_REQUEST = "GET_MOVIE_LIST_REQUEST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAIL = "GET_MOVIE_LIST_FAIL";

export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAIL = "ADD_MOVIE_FAIL";

export const GET_SHOWTIME_REQUEST = "GET_SHOWTIME_REQUEST";
export const GET_SHOWTIME_SUCCESS = "GET_SHOWTIME_SUCCESS";
export const GET_SHOWTIME_FAIL = "GET_SHOWTIME_FAIL";

