export const GET_ROOM_TICKET_REQUEST ="GET_ROOM_TICKET_REQUEST"
export const GET_ROOM_TICKET_SUCCESS ="GET_ROOM_TICKET_SUCCESS"
export const GET_ROOM_TICKET_FAIL = "GET_ROOM_TICKET_FAIL";

export const DANH_SACH_GHE_DANG_CHON ="DANH_SACH_GHE_DANG_CHON"

export const DAT_VE_THANH_CONG ="DAT_VE_THANH_CONG";
export const DAT_VE_THAT_BAI="DAT_VE_THAT_BAI";

export const SHOW_LOADING ="SHOW_LOADING";
export const HIDE_LOADING ="HIDE_LOADING";

export const DAT_GHE ="DAT_GHE";